apiVersion: v1
kind: Service
metadata:
  name: music-streaming-appl-frontend-node
  labels:
    app: music-streaming-appl-frontend
spec:
  type: NodePort
  selector:
    app: music-streaming-appl-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
