# apiVersion: v1
# kind: Service
# metadata:
#   name: music-streaming-appl-admin-svc
#   labels:
#     app: music-streaming-appl-admin
# spec:
#   type: ClusterIP
#   selector:
#     app: music-streaming-appl-admin
#   ports:
#   - protocol: TCP
#     port: 5002
#     targetPort: 5002
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: music-streaming-appl-song-svc
#   labels:
#     app: music-streaming-appl-song
# spec:
#   type: ClusterIP
#   selector:
#     app: music-streaming-appl-song
#   ports:
#   - protocol: TCP
#     port: 5003
#     targetPort: 5003
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: music-streaming-appl-user-svc
#   labels:
#     app: music-streaming-appl-user
# spec:
#   type: ClusterIP
#   selector:
#     app: music-streaming-appl-user
#   ports:
#   - protocol: TCP
#     port: 5001
#     targetPort: 5001
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: music-streaming-appl-frontend-svc
#   labels:
#     app: music-streaming-appl-frontend
# spec:
#   type: ClusterIP
#   selector:
#     app: music-streaming-appl-frontend
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: music-streaming-appl-admin-svc
  labels:
    app: music-streaming-appl-admin
spec:
  type: ClusterIP
  selector:
    app: music-streaming-appl-admin
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: music-streaming-appl-song-svc
  labels:
    app: music-streaming-appl-song
spec:
  type: ClusterIP
  selector:
    app: music-streaming-appl-song
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: music-streaming-appl-user-svc
  labels:
    app: music-streaming-appl-user
spec:
  type: ClusterIP
  selector:
    app: music-streaming-appl-user
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: music-streaming-appl-frontend-svc
  labels:
    app: music-streaming-appl-frontend
spec:
  type: ClusterIP
  selector:
    app: music-streaming-appl-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
